name: async_message_queue_controller
description: An asynchronous message queue controller.
version: 0.1.0
homepage: https://www.example.com
author: Serge Besnard <sbesnard@gmail.com>

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  test: ^1.17.7

